spring:
  config:
    import:
      - classpath:/application-oauth.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yes48?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: yes48
    password: yes48

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    generate-ddl: true
    hibernate:
      hbm2ddl:
        auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


